# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(840, 801)
        MainWindow.setMinimumSize(QtCore.QSize(840, 0))
        MainWindow.setMaximumSize(QtCore.QSize(840, 808))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        MainWindow.setFocusPolicy(QtCore.Qt.WheelFocus)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.Button_Update = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Update.setGeometry(QtCore.QRect(770, 420, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_Update.setFont(font)
        self.Button_Update.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_Update.setMouseTracking(False)
        self.Button_Update.setStyleSheet("#Button_Update{\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 239, 239);\n"
"border-radius: 30px\n"
"\n"
"}")
        self.Button_Update.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Update.setIcon(icon)
        self.Button_Update.setIconSize(QtCore.QSize(50, 50))
        self.Button_Update.setObjectName("Button_Update")
        self.Button_NewAccount = QtWidgets.QPushButton(self.centralwidget)
        self.Button_NewAccount.setGeometry(QtCore.QRect(730, 10, 101, 71))
        self.Button_NewAccount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_NewAccount.setStyleSheet("#Button_NewAccount{\n"
"background-color: rgb(253, 166, 59);\n"
"border-radius: 35px\n"
"\n"
"}")
        self.Button_NewAccount.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/NewAcount.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_NewAccount.setIcon(icon1)
        self.Button_NewAccount.setIconSize(QtCore.QSize(50, 50))
        self.Button_NewAccount.setObjectName("Button_NewAccount")
        self.Button_Login = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Login.setGeometry(QtCore.QRect(10, 10, 101, 71))
        self.Button_Login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_Login.setStyleSheet("#Button_Login{\n"
"background-color: rgb(95, 236, 64);\n"
"border-radius: 35px\n"
"\n"
"}")
        self.Button_Login.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Login.setIcon(icon2)
        self.Button_Login.setIconSize(QtCore.QSize(50, 50))
        self.Button_Login.setObjectName("Button_Login")
        self.GirisDegerler = QtWidgets.QWidget(self.centralwidget)
        self.GirisDegerler.setGeometry(QtCore.QRect(10, 460, 821, 341))
        self.GirisDegerler.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.GirisDegerler.setStyleSheet("#GirisDegerler{\n"
"background-color: qlineargradient(spread:pad, x1:0.119, y1:0.504591, x2:1, y2:0, stop:0.25997 rgba(74, 209, 109, 255), stop:0.691285 rgba(44, 175, 250, 255));\n"
"border-radius: 35px\n"
"}")
        self.GirisDegerler.setObjectName("GirisDegerler")
        self.gridLayout = QtWidgets.QGridLayout(self.GirisDegerler)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(20, 20, 20, 20)
        self.gridLayout.setHorizontalSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.IconSterlin = QtWidgets.QLabel(self.GirisDegerler)
        self.IconSterlin.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.IconSterlin.setFont(font)
        self.IconSterlin.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.332, y1:0.732955, x2:0.770896, y2:0.33, stop:0.353234 rgba(226, 183, 149, 255), stop:0.915423 rgba(254, 255, 167, 255));\n"
"border-radius: 25px\n"
"")
        self.IconSterlin.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.IconSterlin.setFrameShadow(QtWidgets.QFrame.Plain)
        self.IconSterlin.setText("")
        self.IconSterlin.setPixmap(QtGui.QPixmap(":/icons/Sterling.png"))
        self.IconSterlin.setScaledContents(True)
        self.IconSterlin.setObjectName("IconSterlin")
        self.gridLayout.addWidget(self.IconSterlin, 3, 1, 1, 1)
        self.label_Euro = QtWidgets.QLabel(self.GirisDegerler)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_Euro.setFont(font)
        self.label_Euro.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Euro.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_Euro.setObjectName("label_Euro")
        self.gridLayout.addWidget(self.label_Euro, 2, 2, 1, 1)
        self.Sterlin_Degisim = QtWidgets.QLabel(self.GirisDegerler)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Sterlin_Degisim.setFont(font)
        self.Sterlin_Degisim.setObjectName("Sterlin_Degisim")
        self.gridLayout.addWidget(self.Sterlin_Degisim, 3, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.IconGramAltin = QtWidgets.QLabel(self.GirisDegerler)
        self.IconGramAltin.setMaximumSize(QtCore.QSize(50, 50))
        self.IconGramAltin.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.IconGramAltin.setFont(font)
        self.IconGramAltin.setStyleSheet("#IconGramAltin{\n"
"background-color: qlineargradient(spread:pad, x1:0.332, y1:0.732955, x2:0.770896, y2:0.33, stop:0.353234 rgba(226, 183, 149, 255), stop:0.915423 rgba(254, 255, 167, 255));\n"
"border-radius: 25px\n"
"}")
        self.IconGramAltin.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.IconGramAltin.setFrameShadow(QtWidgets.QFrame.Plain)
        self.IconGramAltin.setText("")
        self.IconGramAltin.setTextFormat(QtCore.Qt.RichText)
        self.IconGramAltin.setPixmap(QtGui.QPixmap(":/icons/Gold.png"))
        self.IconGramAltin.setScaledContents(True)
        self.IconGramAltin.setWordWrap(False)
        self.IconGramAltin.setIndent(-1)
        self.IconGramAltin.setOpenExternalLinks(False)
        self.IconGramAltin.setObjectName("IconGramAltin")
        self.gridLayout.addWidget(self.IconGramAltin, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.Altin_Degisim_Icon = QtWidgets.QLabel(self.GirisDegerler)
        self.Altin_Degisim_Icon.setStyleSheet("image: url(:/icons/ArrowsUp .png);")
        self.Altin_Degisim_Icon.setText("")
        self.Altin_Degisim_Icon.setObjectName("Altin_Degisim_Icon")
        self.gridLayout.addWidget(self.Altin_Degisim_Icon, 0, 5, 1, 1)
        self.label_Dolar = QtWidgets.QLabel(self.GirisDegerler)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_Dolar.setFont(font)
        self.label_Dolar.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Dolar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_Dolar.setObjectName("label_Dolar")
        self.gridLayout.addWidget(self.label_Dolar, 1, 2, 1, 1)
        self.Euro_Degisim_Icon = QtWidgets.QLabel(self.GirisDegerler)
        self.Euro_Degisim_Icon.setText("")
        self.Euro_Degisim_Icon.setObjectName("Euro_Degisim_Icon")
        self.gridLayout.addWidget(self.Euro_Degisim_Icon, 2, 5, 1, 1)
        self.Dolar_Degisim_Icon = QtWidgets.QLabel(self.GirisDegerler)
        self.Dolar_Degisim_Icon.setText("")
        self.Dolar_Degisim_Icon.setObjectName("Dolar_Degisim_Icon")
        self.gridLayout.addWidget(self.Dolar_Degisim_Icon, 1, 5, 1, 1)
        self.Euro_Degisim = QtWidgets.QLabel(self.GirisDegerler)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Euro_Degisim.setFont(font)
        self.Euro_Degisim.setObjectName("Euro_Degisim")
        self.gridLayout.addWidget(self.Euro_Degisim, 2, 4, 1, 1)
        self.Sterlin_Degisim_Icon = QtWidgets.QLabel(self.GirisDegerler)
        self.Sterlin_Degisim_Icon.setText("")
        self.Sterlin_Degisim_Icon.setObjectName("Sterlin_Degisim_Icon")
        self.gridLayout.addWidget(self.Sterlin_Degisim_Icon, 3, 5, 1, 1)
        self.Altin_Degisim = QtWidgets.QLabel(self.GirisDegerler)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Altin_Degisim.setFont(font)
        self.Altin_Degisim.setObjectName("Altin_Degisim")
        self.gridLayout.addWidget(self.Altin_Degisim, 0, 4, 1, 1)
        self.Sterlin = QtWidgets.QLabel(self.GirisDegerler)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Sterlin.setFont(font)
        self.Sterlin.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Sterlin.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Sterlin.setObjectName("Sterlin")
        self.gridLayout.addWidget(self.Sterlin, 3, 0, 1, 1)
        self.Dolar_Degisim = QtWidgets.QLabel(self.GirisDegerler)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Dolar_Degisim.setFont(font)
        self.Dolar_Degisim.setObjectName("Dolar_Degisim")
        self.gridLayout.addWidget(self.Dolar_Degisim, 1, 4, 1, 1)
        self.Euro = QtWidgets.QLabel(self.GirisDegerler)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Euro.setFont(font)
        self.Euro.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Euro.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Euro.setObjectName("Euro")
        self.gridLayout.addWidget(self.Euro, 2, 0, 1, 1)
        self.IconEuro = QtWidgets.QLabel(self.GirisDegerler)
        self.IconEuro.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.IconEuro.setFont(font)
        self.IconEuro.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.332, y1:0.732955, x2:0.770896, y2:0.33, stop:0.353234 rgba(226, 183, 149, 255), stop:0.915423 rgba(254, 255, 167, 255));\n"
"border-radius: 25px\n"
"")
        self.IconEuro.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.IconEuro.setFrameShadow(QtWidgets.QFrame.Plain)
        self.IconEuro.setText("")
        self.IconEuro.setPixmap(QtGui.QPixmap(":/icons/Euro.png"))
        self.IconEuro.setScaledContents(True)
        self.IconEuro.setObjectName("IconEuro")
        self.gridLayout.addWidget(self.IconEuro, 2, 1, 1, 1)
        self.IconDolar = QtWidgets.QLabel(self.GirisDegerler)
        self.IconDolar.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.IconDolar.setFont(font)
        self.IconDolar.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0.332, y1:0.732955, x2:0.770896, y2:0.33, stop:0.353234 rgba(226, 183, 149, 255), stop:0.915423 rgba(254, 255, 167, 255));\n"
"border-radius: 25px\n"
"")
        self.IconDolar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.IconDolar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.IconDolar.setText("")
        self.IconDolar.setPixmap(QtGui.QPixmap(":/icons/Dolar.png"))
        self.IconDolar.setScaledContents(True)
        self.IconDolar.setObjectName("IconDolar")
        self.gridLayout.addWidget(self.IconDolar, 1, 1, 1, 1)
        self.label_Sterlin = QtWidgets.QLabel(self.GirisDegerler)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_Sterlin.setFont(font)
        self.label_Sterlin.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_Sterlin.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_Sterlin.setObjectName("label_Sterlin")
        self.gridLayout.addWidget(self.label_Sterlin, 3, 2, 1, 1)
        self.Dolar = QtWidgets.QLabel(self.GirisDegerler)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Dolar.setFont(font)
        self.Dolar.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Dolar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Dolar.setObjectName("Dolar")
        self.gridLayout.addWidget(self.Dolar, 1, 0, 1, 1)
        self.GramAltin = QtWidgets.QLabel(self.GirisDegerler)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.GramAltin.setFont(font)
        self.GramAltin.setStyleSheet("border-color: rgb(255, 0, 0);")
        self.GramAltin.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.GramAltin.setFrameShadow(QtWidgets.QFrame.Plain)
        self.GramAltin.setObjectName("GramAltin")
        self.gridLayout.addWidget(self.GramAltin, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 3, 1, 1)
        self.label_GramAltin = QtWidgets.QLabel(self.GirisDegerler)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_GramAltin.setFont(font)
        self.label_GramAltin.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_GramAltin.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_GramAltin.setObjectName("label_GramAltin")
        self.gridLayout.addWidget(self.label_GramAltin, 0, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 5)
        self.Text_Login = QtWidgets.QPushButton(self.centralwidget)
        self.Text_Login.setGeometry(QtCore.QRect(90, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Text_Login.setFont(font)
        self.Text_Login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Text_Login.setStyleSheet("background-color: rgb(95, 236, 64);\n"
"border-radius: 15px")
        self.Text_Login.setIcon(icon2)
        self.Text_Login.setObjectName("Text_Login")
        self.Text_NewAccount = QtWidgets.QPushButton(self.centralwidget)
        self.Text_NewAccount.setGeometry(QtCore.QRect(590, 60, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Text_NewAccount.setFont(font)
        self.Text_NewAccount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Text_NewAccount.setStyleSheet("background-color: rgb(253, 166, 59);\n"
"border-radius: 18px")
        self.Text_NewAccount.setIcon(icon1)
        self.Text_NewAccount.setObjectName("Text_NewAccount")
        self.Frame_Login = QtWidgets.QFrame(self.centralwidget)
        self.Frame_Login.setGeometry(QtCore.QRect(0, 90, 491, 211))
        self.Frame_Login.setStyleSheet("#Frame_Login{\n"
"background-color: rgb(231, 255, 106);\n"
"border-radius: 100px\n"
"\n"
"}")
        self.Frame_Login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_Login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_Login.setObjectName("Frame_Login")
        self.formFrame = QtWidgets.QFrame(self.Frame_Login)
        self.formFrame.setGeometry(QtCore.QRect(50, 50, 391, 91))
        self.formFrame.setObjectName("formFrame")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(42, 255, 231);\n"
"border-radius : 10px\n"
"")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.Frame_Login_User = QtWidgets.QLineEdit(self.formFrame)
        self.Frame_Login_User.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Frame_Login_User.setFont(font)
        self.Frame_Login_User.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Frame_Login_User.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Frame_Login_User.setToolTip("")
        self.Frame_Login_User.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Frame_Login_User.setAutoFillBackground(False)
        self.Frame_Login_User.setStyleSheet("background-color: rgb(210, 255, 167);\n"
"font: 75 9pt \"MS Shell Dlg 2\";")
        self.Frame_Login_User.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Frame_Login_User.setText("")
        self.Frame_Login_User.setObjectName("Frame_Login_User")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Frame_Login_User)
        self.label_2 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(42, 255, 231);\n"
"border-radius : 10px\n"
"")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.Frame_Login_Pass = QtWidgets.QLineEdit(self.formFrame)
        self.Frame_Login_Pass.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Frame_Login_Pass.setFont(font)
        self.Frame_Login_Pass.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Frame_Login_Pass.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Frame_Login_Pass.setStyleSheet("background-color: rgb(210, 255, 167);\n"
"font: 75 9pt \"MS Shell Dlg 2\";")
        self.Frame_Login_Pass.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.Frame_Login_Pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Frame_Login_Pass.setObjectName("Frame_Login_Pass")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Frame_Login_Pass)
        self.Text_Login_2 = QtWidgets.QPushButton(self.Frame_Login)
        self.Text_Login_2.setGeometry(QtCore.QRect(390, 130, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Text_Login_2.setFont(font)
        self.Text_Login_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Text_Login_2.setStyleSheet("\n"
"border-radius: 20px")
        self.Text_Login_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/GirisIconu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Text_Login_2.setIcon(icon3)
        self.Text_Login_2.setIconSize(QtCore.QSize(50, 65))
        self.Text_Login_2.setObjectName("Text_Login_2")
        self.LCD_clock = QtWidgets.QLCDNumber(self.centralwidget)
        self.LCD_clock.setGeometry(QtCore.QRect(260, 140, 341, 91))
        self.LCD_clock.setStyleSheet("border-image: url(:/Background/ClockBackground.jpg);\n"
"border-radius:  20px")
        self.LCD_clock.setObjectName("LCD_clock")
        self.Frame_NewAccount = QtWidgets.QFrame(self.centralwidget)
        self.Frame_NewAccount.setGeometry(QtCore.QRect(300, 100, 491, 221))
        self.Frame_NewAccount.setStyleSheet("#Frame_NewAccount{\n"
"background-color: rgb(255, 170, 0);\n"
"border-radius: 100px\n"
"}")
        self.Frame_NewAccount.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_NewAccount.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_NewAccount.setObjectName("Frame_NewAccount")
        self.formFrame_4 = QtWidgets.QFrame(self.Frame_NewAccount)
        self.formFrame_4.setGeometry(QtCore.QRect(30, 30, 431, 131))
        self.formFrame_4.setObjectName("formFrame_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formFrame_4)
        self.formLayout_4.setContentsMargins(10, 10, 10, 10)
        self.formLayout_4.setHorizontalSpacing(20)
        self.formLayout_4.setVerticalSpacing(10)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtWidgets.QLabel(self.formFrame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"border-radius : 10px\n"
"")
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.Frame_NewAccount_User = QtWidgets.QLineEdit(self.formFrame_4)
        self.Frame_NewAccount_User.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Frame_NewAccount_User.setFont(font)
        self.Frame_NewAccount_User.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Frame_NewAccount_User.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Frame_NewAccount_User.setToolTip("")
        self.Frame_NewAccount_User.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Frame_NewAccount_User.setAutoFillBackground(False)
        self.Frame_NewAccount_User.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 9pt \"MS Shell Dlg 2\";")
        self.Frame_NewAccount_User.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Frame_NewAccount_User.setText("")
        self.Frame_NewAccount_User.setObjectName("Frame_NewAccount_User")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Frame_NewAccount_User)
        self.label_8 = QtWidgets.QLabel(self.formFrame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"border-radius : 10px\n"
"")
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.Frame_NewAccount_Gmail = QtWidgets.QLineEdit(self.formFrame_4)
        self.Frame_NewAccount_Gmail.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Frame_NewAccount_Gmail.setFont(font)
        self.Frame_NewAccount_Gmail.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Frame_NewAccount_Gmail.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Frame_NewAccount_Gmail.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 9pt \"MS Shell Dlg 2\";")
        self.Frame_NewAccount_Gmail.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Frame_NewAccount_Gmail.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.Frame_NewAccount_Gmail.setObjectName("Frame_NewAccount_Gmail")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Frame_NewAccount_Gmail)
        self.label_9 = QtWidgets.QLabel(self.formFrame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"border-radius : 10px\n"
"")
        self.label_9.setObjectName("label_9")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.formFrame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"border-radius : 10px\n"
"")
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.Frame_NewAccount_Pass = QtWidgets.QLineEdit(self.formFrame_4)
        self.Frame_NewAccount_Pass.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Frame_NewAccount_Pass.setFont(font)
        self.Frame_NewAccount_Pass.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Frame_NewAccount_Pass.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Frame_NewAccount_Pass.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 9pt \"MS Shell Dlg 2\";")
        self.Frame_NewAccount_Pass.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.Frame_NewAccount_Pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Frame_NewAccount_Pass.setObjectName("Frame_NewAccount_Pass")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Frame_NewAccount_Pass)
        self.Frame_NewAccount_PassConfirm = QtWidgets.QLineEdit(self.formFrame_4)
        self.Frame_NewAccount_PassConfirm.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Frame_NewAccount_PassConfirm.setFont(font)
        self.Frame_NewAccount_PassConfirm.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Frame_NewAccount_PassConfirm.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Frame_NewAccount_PassConfirm.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 9pt \"MS Shell Dlg 2\";")
        self.Frame_NewAccount_PassConfirm.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.Frame_NewAccount_PassConfirm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Frame_NewAccount_PassConfirm.setObjectName("Frame_NewAccount_PassConfirm")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Frame_NewAccount_PassConfirm)
        self.Button_CreateAccount = QtWidgets.QPushButton(self.Frame_NewAccount)
        self.Button_CreateAccount.setGeometry(QtCore.QRect(380, 160, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Button_CreateAccount.setFont(font)
        self.Button_CreateAccount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_CreateAccount.setStyleSheet("\n"
"border-radius: 20px")
        self.Button_CreateAccount.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/CreateIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_CreateAccount.setIcon(icon4)
        self.Button_CreateAccount.setIconSize(QtCore.QSize(50, 50))
        self.Button_CreateAccount.setShortcut("")
        self.Button_CreateAccount.setDefault(True)
        self.Button_CreateAccount.setObjectName("Button_CreateAccount")
        self.checkBox = QtWidgets.QCheckBox(self.Frame_NewAccount)
        self.checkBox.setGeometry(QtCore.QRect(80, 180, 281, 20))
        self.checkBox.setObjectName("checkBox")
        self.Button_Exit = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Exit.setGeometry(QtCore.QRect(10, 0, 91, 81))
        self.Button_Exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button_Exit.setStyleSheet("#Button_Exit{\n"
"\n"
"\n"
"border-radius: 35px\n"
"\n"
"}")
        self.Button_Exit.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/exit icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_Exit.setIcon(icon5)
        self.Button_Exit.setIconSize(QtCore.QSize(50, 50))
        self.Button_Exit.setObjectName("Button_Exit")
        self.selamla = QtWidgets.QLabel(self.centralwidget)
        self.selamla.setGeometry(QtCore.QRect(280, 410, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.selamla.setFont(font)
        self.selamla.setStyleSheet("color: rgb(0, 0, 0);")
        self.selamla.setObjectName("selamla")
        self.Button_NewAccount.raise_()
        self.Button_Login.raise_()
        self.GirisDegerler.raise_()
        self.Button_Update.raise_()
        self.Text_Login.raise_()
        self.Text_NewAccount.raise_()
        self.Frame_Login.raise_()
        self.LCD_clock.raise_()
        self.Frame_NewAccount.raise_()
        self.Button_Exit.raise_()
        self.selamla.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Button_Update, self.Button_NewAccount)
        MainWindow.setTabOrder(self.Button_NewAccount, self.Button_Login)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DovizProjesi"))
        self.label_Euro.setText(_translate("MainWindow", "-"))
        self.Sterlin_Degisim.setText(_translate("MainWindow", "%0.00"))
        self.label_Dolar.setText(_translate("MainWindow", "-"))
        self.Euro_Degisim.setText(_translate("MainWindow", "%0.00"))
        self.Altin_Degisim.setText(_translate("MainWindow", "%0.00"))
        self.Sterlin.setText(_translate("MainWindow", "Sterlin"))
        self.Dolar_Degisim.setText(_translate("MainWindow", "%0.00"))
        self.Euro.setText(_translate("MainWindow", "Euro"))
        self.label_Sterlin.setText(_translate("MainWindow", "-"))
        self.Dolar.setText(_translate("MainWindow", "Dolar"))
        self.GramAltin.setText(_translate("MainWindow", "Gram Altin"))
        self.label_GramAltin.setText(_translate("MainWindow", "-"))
        self.Text_Login.setText(_translate("MainWindow", "LOGIN"))
        self.Text_NewAccount.setText(_translate("MainWindow", "NEW ACCOUNT"))
        self.label.setText(_translate("MainWindow", "User Name "))
        self.label_2.setText(_translate("MainWindow", "User Password"))
        self.label_7.setText(_translate("MainWindow", "User Name "))
        self.label_8.setText(_translate("MainWindow", "Gmail Adress "))
        self.label_9.setText(_translate("MainWindow", "User Password"))
        self.label_10.setText(_translate("MainWindow", "Confrim Password"))
        self.checkBox.setText(_translate("MainWindow", "GUNCELHABERLER ICIN BANA MAIL GONDER"))
        self.selamla.setText(_translate("MainWindow", "TextLabel"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
